### ISSUE TITLE
Missing path_expander dependency?

### ISSUE THREAD

**Issue by blowmage** [seattlerb/minitest-autotest#16]
I upgraded a project and got the following when running `autotest`:

```
$ bundle exec autotest
Traceback (most recent call last):
	5: from MY_PROJECT/bin/autotest:25:in `<main>'
	4: from MY_PROJECT/bin/autotest:25:in `load'
	3: from MY_PROJECT/gems/minitest-autotest-1.1.0/bin/autotest:3:in `<top (required)>'
	2: from MY_PROJECT/gems/minitest-autotest-1.1.0/bin/autotest:3:in `require'
	1: from MY_PROJECT/gems/minitest-autotest-1.1.0/lib/autotest.rb:4:in `<top (required)>'
MY_PROJECT/gems/minitest-autotest-1.1.0/lib/autotest.rb:4:in `require': cannot load such file -- path_expander (LoadError)
```

Adding it to my Gemfile works.

```ruby
gem "path_expander"
```

**Comment by zenspider** [comment]
OOPS! You’re totally right. I’ll get that out shortly. Thank you!

**Comment by zenspider** [comment]
released 4 days ago...
