### ISSUE TITLE
restart issue

### ISSUE THREAD

**Issue by bhenderson** [seattlerb/minitest-autotest#3]
I'm getting an error when I modify .autotest file.

```
Detected change to .autotest, restarting
Unhandled exception: Address already in use - connect(2) for "/tmp/minitest.23138"
/home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/unix.rb:41:in `initialize'
  /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/unix.rb:41:in `open'
  /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/unix.rb:41:in `open_server'
  /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:764:in `block in open_server'
  /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:762:in `each'
  /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:762:in `open_server'
  /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:770:in `open_server'
  /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:1373:in `initialize'
  /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:1664:in `new'
  /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:1664:in `start_service'
  /home/bhenderson/.gem/gems/minitest-server-1.0.1/lib/minitest/server.rb:15:in `run'
  /home/bhenderson/prog/github/minitest-autotest/lib/autotest.rb:237:in `run'
  /home/bhenderson/prog/github/minitest-autotest/lib/autotest.rb:137:in `run'
  /home/bhenderson/prog/github/minitest-autotest/bin/autotest:6:in `<main>'
Quitting
/home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/unix.rb:41:in `initialize': Address already in use - connect(2) for "/tmp/minitest.23138" (Errno::EADDRINUSE)
        from /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/unix.rb:41:in `open'
        from /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/unix.rb:41:in `open_server'
        from /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:764:in `block in open_server'
        from /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:762:in `each'
        from /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:762:in `open_server'
        from /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:770:in `open_server'
        from /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:1373:in `initialize'
        from /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:1664:in `new'
        from /home/bhenderson/.multiruby/install/2.1.2/lib/ruby/2.1.0/drb/drb.rb:1664:in `start_service'
        from /home/bhenderson/.gem/gems/minitest-server-1.0.1/lib/minitest/server.rb:15:in `run'
        from /home/bhenderson/prog/github/minitest-autotest/lib/autotest.rb:237:in `run'
        from /home/bhenderson/prog/github/minitest-autotest/lib/autotest.rb:137:in `run'
        from /home/bhenderson/prog/github/minitest-autotest/bin/autotest:6:in `<main>'
```

also, seems like seattlerb/zentest#44 was not carried over (double error output)

**Comment by zenspider** [comment]
Ah! Good find! This is trying to bring up the server again w/o a proper close

**Comment by zenspider** [comment]
Can you file the second issue separately (and/or throw in a PR).

**Comment by bhenderson** [comment]
done. thanks #5

**Comment by zenspider** [comment]
@bhenderson can you also test out the recent PR to see if it helps?

**Comment by bhenderson** [comment]
Hey Ryan. I'm out on leave for the next 2 weeks. I'll take a look when I
get back.
